FROM python:3.8.7-slim-buster

ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1

RUN apt-get -qq update \
    && apt-get install -y gcc libffi-dev libssl-dev \
    && pip install esptool \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get remove -y libssl-dev libffi-dev gcc \
    && apt-get autoremove -y
