FROM debian:buster

RUN apt-get -qq update \
    && apt-get install -y gettext-base moreutils curl python3 python3-distutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 

RUN python3 get-pip.py

RUN pip install --upgrade websockets 
